### ISSUE TITLE
I want add DeepseekCoder-v2-15.7B-instruct model , any tips  or guide?

### ISSUE THREAD

**Issue by yourchanges** [Deka-AI-Coding/registry-tabby#2]
I always use your model registry, thank you !

but now , I want add DeepseekCoder-v2-15.7B-instruct model , any tips  or guide?

**Comment by SpeedCrash100** [comment]
Hi, it is very simple. When I used this, I did it in such order:
1. Get tags of interesting model: [In your case it is located here](https://ollama.com/library/deepseek-coder-v2/tags)
2. File [./meta/models.yaml](https://github.com/Deka-AI-Coding/registry-tabby/blob/main/meta/models.yaml) contains models definitions.
  2.1. Open the file and add new entry:
    
      ```yml
      - name: deepseek-coder-v2 #< This name can be found in main page of model
      - tags:
         - tag1
         - tag2
      ```

  2.2. If there are too much tags you can copy whole block of tags from the page and apply some regexp substitutions:
    2.2.1. Replace `.*Updated.*\n` with `` (nothing) to leave only tags
    2.2.2. Replace `^(\w)` with ```    - $1``` to make them yaml array
2.3. Next step is add prompt_template if model support FIM. `deepseek-coder-v2` uses same from v1, I believe, so you can paste [the old one](https://github.com/Deka-AI-Coding/registry-tabby/blob/06d3bdd0a264ce009f3b5ffbd0102c10d63783ef/meta/models.yaml#L180)
2.4 For chat support, specify `chat_template` as well. Ollama changes [it](https://ollama.com/library/deepseek-coder-v2/blobs/b321cd7de6c7) so it should be changed too.
3. The final step is generation of updated registry. You need cargo to do that. To do that call if you or on linux:
```bash
make all
```
or do this step manually by deleting `model.json` and run:
```
cargo run --release -- meta/models.yaml models.json
```

I've done all steps above in [commit](https://github.com/Deka-AI-Coding/registry-tabby/commit/055322dc7173879b45142269492546055b4b46d8). You can use this as an example when want to add new models. Feel free to ask more question and submit Pull Request with new models next time. 

Check out the note in [README.md](https://github.com/Deka-AI-Coding/registry-tabby?tab=readme-ov-file#passive-maintenance-notice). If you can start Ollama near Tabby, you should switch to ollama api connector. See: https://tabby.tabbyml.com/docs/administration/model/#ollama 

I've added deepseek-coder-v2, `Deka-AI-Coding/deepseek-coder-v2:16b-lite-base-q4_0` for code and `Deka-AI-Coding/deepseek-coder-v2:16b-lite-instruct-q4_0` for chat. Have not checked them, through.

**Comment by yourchanges** [comment]
@SpeedCrash100  thank you !!!, I'll have a try.
